### PR TITLE
Use relation's id for ToMany component name

### PR DESCRIPTION
**Pull request by jiripudil**

### CODE REVIEW

**Comment by jiripudil** [comment]
bump

please-guy

**Comment by fprochazka** [comment]
sniwftr

**Comment by fprochazka** [comment]
@jiripudil thank you :D

**Comment by fprochazka** [comment]
Now for real... is anybody still using this?

**Comment by jiripudil** [comment]
Not really :D

(I'm still using this package due to the lack of will to rewrite the code, but I avoided these to-many containers in the end because they seemed to be too complicated anyway)

**Pull request merged**
